apiVersion: v1
kind: Service
metadata:
  name: micado-socket-service
spec:
  type: LoadBalancer
  selector:
    app: micado-socket
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
