version: "3.9"
services:
  prometheus:
    image: prom/prometheus
    restart: always 
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
  grafana:
    image: grafana/grafana
    restart: always 
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
  deconz-prometheus-exporter:
    image: hakonamdal/deconz-prometheus-exporter
    restart: always 
    ports:
      - 8080:8080
    environment:
      - DECONZ_URL=...
      - DECONZ_API_KEY=...
volumes:
  prometheus:
  grafana: