apiVersion: v1
kind: Service
metadata:
  name: kartserver-socket-service
spec:
  type: LoadBalancer
  selector:
    app: kartserver-socket
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
