version: "3.9"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  deconz-exporter:
    image: solsson/prometheus-deconz-exporter
    ports:
      - 8080:8080
    command:
      - --host=100.116.242.20
      - --key=${DECONZ_API_KEY}
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
