global:
  scrape_interval: 60s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: "deconz"
    static_configs:
      - targets:
          - "deconz-exporter:8080"
